name: Build Firmware Protocol Debugger GUI
on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-protocol-debugger-gui-${{ matrix.os }}
          path: apps/firmware-protocol-debugger-gui/dist/slimevr-firmware-protocol-debugger-gui*
